sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t circleci-awscli .
      - docker images
      - docker tag circleci-awscli $DOCKER_USERNAME/circleci-awscli
      - docker push $DOCKER_USERNAME/circleci-awscli